export default class Struggle {
    name: string;
    dbName: string;
    url: string;
    provider: string;
    host: string;
    pass: string;
    port: number;
    db: any;
    method: any;
    value: any;
    table: any;
    key: any;
    chainable: boolean;
    sort: any;
    _reverse: boolean;
    _count: boolean;
    _update: any;
    _insert: any;
    query: string;
    constructor(options: any);
    init(): Promise<void>;
    destroy(): void | this;
    select(value: any): this;
    from(table: any): this;
    where(key: any): this;
    create(value: any): this;
    drop(value: any): this;
    delete(value: any): this;
    update(table: any): this;
    set(_update: any): this;
    count(): this;
    order(): this;
    reverse(): this;
    insert(_insert: any): this;
    into(table: any): this;
    raw(query: any): this;
    run(): Promise<unknown>;
}
